name: PHReplacer
version: 1.2
author: xBuhari
main: xbuhari.pw.PHReplacer.Main
softdepend:
  - PlaceholderAPI
  - MVdWPlaceholderAPI
commands:
  phreplacer:
    description: Main Command
    aliases:
      - phr